order of operations figured out - restore contained files from snapshot

diff --git a/05-ec2/lab5.4.4.yml b/05-ec2/lab5.4.4.yml
--- a/05-ec2/lab5.4.4.yml
+++ b/05-ec2/lab5.4.4.yml
@@ -26,7 +26,7 @@ Resources:
   LaunchTemplate:
     Type: AWS::EC2::LaunchTemplate
     Properties:
-      LaunchTemplateName: lab512-su-jmd-winsvr
+      LaunchTemplateName: lab512-su-jmd-nix
       LaunchTemplateData:
         KeyName: lab544-su-jmd
         SecurityGroupIds:
@@ -50,6 +50,31 @@ Resources:
               # mount the volume on current boot
               mount -a
               echo "foo" >> /mnt/xvdh/rabbit
+  LaunchTemplateRestore:
+    Type: AWS::EC2::LaunchTemplate
+    Properties:
+      LaunchTemplateName: lab512-su-jmd-restore
+      LaunchTemplateData:
+        KeyName: lab544-su-jmd
+        SecurityGroupIds:
+          - !GetAtt SecurityGroup.GroupId
+        InstanceType: t2.small
+        IamInstanceProfile: 
+          Name: !Ref InstanceProfile
+        UserData: 
+            Fn::Base64: !Sub | 
+              #!/bin/bash -xe
+              apt update
+              apt -y install python-setuptools
+              # mkdir aws-cfn-bootstrap-latest
+              # curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1
+              # easy_install aws-cfn-bootstrap-latest
+              # /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource Nix --region ${AWS::Region}
+              # /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Nix --region ${AWS::Region}
+              mkdir /mnt/xvdh
+              echo "/dev/xvdh       /mnt/xvdh   ext4    defaults,nofail 0       2" >> /etc/fstab
+              # mount the volume on current boot
+              mount -a
   SecurityGroup:
     Type: AWS::EC2::SecurityGroup
     Properties: 
@@ -72,6 +97,11 @@ Outputs:
     Value: !Ref LaunchTemplate
     Export:
       Name:  !Sub ${AWS::StackName}-launchtemplate
+  LaunchTemplateRestore:
+    Description: "launch template for import for restore"
+    Value: !Ref LaunchTemplateRestore
+    Export:
+      Name:  !Sub ${AWS::StackName}-launchtemplaterestore
   
       
 #Microsoft Windows Server 2016 Base - ami-0088977e66ac3915d
