splitting cloudformation to second template for instance

diff --git a/05-ec2/lab5.4.4.yml b/05-ec2/lab5.4.4.yml
--- a/05-ec2/lab5.4.4.yml
+++ b/05-ec2/lab5.4.4.yml
@@ -27,60 +27,29 @@ Resources:
     Type: AWS::EC2::LaunchTemplate
     Properties:
       LaunchTemplateName: lab512-su-jmd-winsvr
-      IamInstanceProfile: 
-        Name: !Ref InstanceProfile
-      UserData: 
-          Fn::Base64: !Sub | 
-            #!/bin/bash -xe
-            apt update
-            apt -y install python-setuptools
-            mkdir aws-cfn-bootstrap-latest
-            curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1
-            easy_install aws-cfn-bootstrap-latest
-            /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource Nix --region ${AWS::Region}
-            /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Nix --region ${AWS::Region}
       LaunchTemplateData:
+        KeyName: lab544-su-jmd
         SecurityGroupIds:
           - !GetAtt SecurityGroup.GroupId
-  Nix:
-    Type: AWS::EC2::Instance
-    Properties: 
-      LaunchTemplate: 
-        LaunchTemplateId: !Ref LaunchTemplate
-        Version: "1"
-      ImageId: "ami-0739f8cdb239fe9ae"
-      AvailabilityZone: us-east-1a
-    Metadata: 
-      AWS::CloudFormation::Init: 
-        config: 
-          sources: 
-            /etc/cloudwatchagent: https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip
-          commands:
-            installCloudwatch: 
-              command: ./install.sh
-              cwd: /etc/cloudwatchagent
-            launchCloudwatch: 
-              command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s
-            volumeMountPoint:
-              command: mkdir /mnt/ebsv
-            volumeFS:
-              command: mkfs -t ext4 /dev/ebsv
-            volumeFSTab:
-              command: echo "/dev/ebsv       /mnt/ebsv   ext4    defaults,nofail 0       2" >> /etc/fstab
-            volumeMount:
-              command: mount -a      
-  Volume:
-    Type: AWS::EC2::Volume
-    Properties:
-      AvailabilityZone: !GetAtt Nix.AvailabilityZone
-      Size: 4
-      VolumeType: gp2
-  VolumeAttachment:
-    Type: AWS::EC2::VolumeAttachment
-    Properties:
-      Device: /dev/sdh
-      InstanceId: !Ref Nix
-      VolumeId: !Ref Volume
+        InstanceType: t2.small
+        IamInstanceProfile: 
+          Name: !Ref InstanceProfile
+        UserData: 
+            Fn::Base64: !Sub | 
+              #!/bin/bash -xe
+              apt update
+              apt -y install python-setuptools
+              # mkdir aws-cfn-bootstrap-latest
+              # curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1
+              # easy_install aws-cfn-bootstrap-latest
+              # /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource Nix --region ${AWS::Region}
+              # /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Nix --region ${AWS::Region}
+              mkdir /mnt/xvdh
+              mkfs -t ext4 /dev/xvdh
+              echo "/dev/xvdh       /mnt/xvdh   ext4    defaults,nofail 0       2" >> /etc/fstab
+              # mount the volume on current boot
+              mount -a
+              echo "foo" >> /mnt/xvdh/rabbit
   SecurityGroup:
     Type: AWS::EC2::SecurityGroup
     Properties: 
@@ -96,18 +65,14 @@ Resources:
           IpProtocol: icmp
           FromPort: -1
           ToPort: -1
-  EIP:
-    Type: AWS::EC2::EIP
-    Properties:
-      InstanceId: !Ref Nix
 
 Outputs:
-  PublicIP:
-    Description: Nix PubIP
-    Value: !Ref EIP
+  LaunchTemplateOut:
+    Description: "launch template for import"
+    Value: !Ref LaunchTemplate
     Export:
-      Name:  !Sub ${AWS::StackName}-pubip
-
+      Name:  !Sub ${AWS::StackName}-launchtemplate
+  
       
 #Microsoft Windows Server 2016 Base - ami-0088977e66ac3915d
 #Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-0739f8cdb239fe9ae
